default_language_version:
    python: python3.6
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: requirements-txt-fixer
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
